### ISSUE TITLE
Question about exit and entrance rates

### ISSUE THREAD

**Issue by MokeEire** [economicroundtable/homeless_LA#1]
In the Annualized Model, you arrive at a constant exit rate of 16.5%.  In an attempt to model the monthly fluctuations in the homeless population, I looked at the weekly 'newly homeless' estimate (B in the model) which is 1513.  In a very simplistic model:

PIT + 4\*B (monthly entrance rate) - ExitRate\*PIT

The estimate of the homeless population is decreasing until the population count reaches ~36000.  I am assuming this is not the case given that homelessness rates have been increasing.  This simple model is assuming a constant exit and entrance rate, but I believe this may suggest that the entrance rate is underestimated or the exit rate is overestimated.  

However it also seems likely that the measures are not equivalent, given that the model derives the exit rate from ~8000 observations and the exit rate is an estimated count.

My question very broadly - how would one go about estimating monthly changes in the homeless population? However, if you could illuminate any misunderstandings I have made with the data, that would also be incredibly helpful.

**Comment by jcarlen** [comment]
Thanks for your question.  A few thoughts:

1.  The exit rate is only meant to apply to monthly exit rates in the first year of homelessness. For a few reasons we did not attempt to estimate such an exit rate for people who have been homeless for at least a year, and I assume it would be lower. Since the >1yr group accounts for roughly half of the point in time population, applying a different (lower) exit rate to them in your simplified model could lead to an estimate that’s more in line with the increases in the number of homeless people we have observed. Since we were ultimately trying to estimate the number of people who experience homeless in the course of a year, and only broke down the duration for the <1yr group (see Table 3), we avoided the even more difficult task of estimating exit rates for those who have been homeless for over a year. If we wanted to estimate monthly changes in the homeless population I think we would have to incorporate such an estimate. 

2. Our model allows us to estimate the number of new entrants to homelessness each day (see Table 2 in the report), which would not be reliable if we used the number of people who reported being in their first day of homelessness in survey data. This could help in building an estimate of changes in population size over a given time interval. 

3. I think it shows a limitation in the data (not specific to any model) that our estimated exit rates were constant.  I had expected the exit rates to decrease over the first year, as the social, physical and mental effects of homelessness build up over time. I didn't see a way around that without overly massaging the data, but I'm very open to suggestions.

**Comment by MokeEire** [comment]
There's the issue.  I could feel there was something I was missing.

So the question remaining is how to estimate exit rates for the >1yr group.  However in the Sheltered data, the Current_Stint_Duration variable offers little help, but given the numbers in the Unsheltered data (just glancing at 2016-2017) it appears to be close to non-existent.  To say that, of course, relies on a myriad of assumptions.  

Does ERT have any plans in the future to try to estimate long-term homelessness exit rates?  In the absence of any kind of identifying variables, what kind of analysis is possible?

**Comment by jcarlen** [comment]
Although it's definitely an important question, ERT doesn't have plans to tackle it right now due to funding and data limitations. I think that a really meaningful analysis would have to incorporate data external to the the annual counts, which are meant for point-in-time estimates. Ideally you'd have longitudinal data for a sample of persistently homeless people. Margot Kushel at UCSF is doing amazing work in this vein, but restricted to older adults in Oakland. (e.g. see https://www.nhchc.org/wp-content/uploads/2017/06/hch-hope-home-2017-talk.pdf)

**Comment by economicrt-la** [comment]
We're now looking at longitudinal data for about 1M people who experienced homelessness sometime within a 14-year time window and are able to see entrance and exit rates for persistently homeless individuals. One of the things were seeing is multiple homeless stints. Only exits and re-entries within a year matter for the annual population model, but cumulative time homeless is important for understanding population composition. A constraint with the longitudinal data is that it includes people who are couchsurfing, which is a broader population than the people in the homeless count, who are screened to meet HUD's narrower criteria of sleeping in a place not meant for human habitation. The longitudinal data will come out in a future report. In the meantime, we'll share results with anyone who's interested.
